# Generated by Django 4.2.1 on 2023-05-12 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarked_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
