# Generated by Django 4.2.1 on 2023-05-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userbookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBookmark',
        ),
    ]
